/**
 * Icon allowlist — names that the FeatureGrid editor accepts.
 * Keep curated, expand only when a real PR needs a new icon.
 * Loaded dynamically from `lucide-react` at render time.
 */
export const ICON_ALLOWLIST = [
  "Sparkles",
  "Zap",
  "Rocket",
  "Star",
  "Heart",
  "Check",
  "CheckCircle",
  "CircleCheck",
  "Award",
  "Crown",
  "Trophy",
  "Target",
  "TrendingUp",
  "BarChart3",
  "PieChart",
  "LineChart",
  "Users",
  "User",
  "UserCheck",
  "MessageCircle",
  "MessageSquare",
  "Mail",
  "Phone",
  "Globe",
  "MapPin",
  "Calendar",
  "Clock",
  "Compass",
  "Camera",
  "Image",
  "Palette",
  "Brush",
  "PenTool",
  "Layers",
  "Box",
  "Package",
  "ShoppingBag",
  "ShoppingCart",
  "Tag",
  "Gift",
  "Lock",
  "Unlock",
  "Shield",
  "ShieldCheck",
  "Key",
  "Code",
  "Terminal",
  "Cpu",
  "Database",
  "Server",
  "Cloud",
  "Wifi",
  "Lightbulb",
  "Brain",
  "Wand2",
  "Activity",
  "Flame",
  "Sun",
  "Moon",
  "Settings",
  "Sliders",
  "Filter",
  "Search",
  "Eye",
  "Building2",
  "Home",
  "Briefcase",
  "GraduationCap",
  "BookOpen",
  "FileText",
  "Folder",
  "Bookmark",
  "Bell",
  "Smile",
  "ThumbsUp",
  "Play",
  "Pause",
  "ArrowRight",
  "ArrowUpRight",
  "ChevronRight",
  "Plus",
  "Minus",
] as const;

export type AllowedIcon = (typeof ICON_ALLOWLIST)[number];

export function isAllowedIcon(name: string): name is AllowedIcon {
  return (ICON_ALLOWLIST as readonly string[]).includes(name);
}
